version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    platform: linux/amd64
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '9200:9100'
    expose:
      - '9100'
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookreviews
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3500:3000'
    expose:
      - '3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:9100
    depends_on:
      - backend

volumes:
  mongo_data:
