version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    platform: linux/amd64
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '9100:9100'
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookreviews
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  mongo_data:
